name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: books_faux_lyfe_test
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '23.1'
          elixir-version: '1.11.0'
      - uses: actions/setup-node@v1
        with:
          node-version: 14.12.0
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Cache build
        uses: actions/cache@v2
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-build-
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/assets/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
      - run: |
          mix deps.get
          npm ci --prefix assets
      - run: |
          mix compile --warnings-as-errors
          mix test
        env:
          MIX_ENV: test
      - run: |
          mix hex.audit
          mix hex.outdated
